def build_frame(seq: str, chain: str) -> str:
    seq_for_scalop: str = ""
    if chain == "L1":
        seq_for_scalop = "NFMLTQPHSVSESPGKTVTISC" + seq + "WYQRRPGSAPTTVIYEDNQRPSGVPDRFSASIDSSSNSASLTISGLKTEDEADYYCQSYDSSNWVFGGGTKLTVLGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS"
    elif chain == "L2":
        seq_for_scalop = "SDVGTFDLVSWYQQYPGKAPKLIIY" + seq + "GVSDRFSGSKSGNTASLTISGLQAEDEADYYCSSYAGSVVFGGGTKLTVLGQPKGAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS"
    elif chain == "L3":
        seq_for_scalop = "SDVGTFDLVSWYQQYPGKAPKLIIYEGSRRPSGVSDRFSGSKSGNTASLTISGLQAEDEADYYC" + seq + "FGGGTKLTVLGQPKGAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPVKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPTECS"
    elif chain == "H1":
        seq_for_scalop = "VQLQESGGCLVQAGGSLRLSCAAS" + seq + "TIGWFRQAPGKEREFVAAIHWDGGQTYYADSVKGRFTISRDNAKNTVYLQMNSLKPEDTAVYYCAARGRRYFDFTYSDVYDYWGQGTQVTVS"
    elif chain == "H2":
        seq_for_scalop = "VQLQESGGCLVQAGGSLRLSCAASGSTFSTYTIGWFRQAPGKEREFVAAI" + seq + "TYYADSVKGRFTISRDNAKNTVYLQMNSLKPEDTAVYYCAARGRRYFDFTYSDVYDYWGQGTQVTVS"
    return seq_for_scalop
